<div class="row">
    <div class="col">
        <a href="?op=rn_generator" class="btn btn-dark color"> Gerador de números aleatórios </a>&nbsp;
    </div>
    <div class="col">
        <a href="?op=" class="btn btn-dark color"> Em breve </a>&nbsp;
    </div>
</div>
<br>
<div class="row">
    <div class="col">
        <a href="?op=csv2json" class="btn btn-dark color flex-sm-fill text-sm-center"> Conversor CSV / JSON </a>&nbsp;
    </div>
    <div class="col">
        <a href="?op=json2csv" class="btn btn-dark color"> Conversor JSON / CSV </a>&nbsp;
    </div>
</div>
<br>
<div class="row">
    <div class="col">
        <a href="?op=" class="btn btn-dark color"> Em breve </a>&nbsp;
    </div>
    <div class="col">
        <a href="?op=" class="btn btn-dark color"> Em breve </a>&nbsp;
    </div>
</div>